import { MimeCategory } from "./typedef";


export const CUSTOM_MAP: Record<string, string> = {
  // Images
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  gif: "image/gif",
  webp: "image/webp",
  bmp: "image/bmp",
  tiff: "image/tiff",
  tif: "image/tiff",
  ico: "image/x-icon",
  svg: "image/svg+xml",
  heic: "image/heic",
  heif: "image/heif",
  avif: "image/avif",

  // Audio
  mp3: "audio/mpeg",
  wav: "audio/wav",
  ogg: "audio/ogg",
  oga: "audio/ogg",
  flac: "audio/flac",
  aac: "audio/aac",
  m4a: "audio/mp4",
  opus: "audio/opus",
  mid: "audio/midi",
  midi: "audio/midi",
  weba: "audio/webm",

  // Video
  mp4: "video/mp4",
  webm: "video/webm",
  mkv: "video/x-matroska",
  avi: "video/x-msvideo",
  mov: "video/quicktime",
  wmv: "video/x-ms-wmv",
  flv: "video/x-flv",
  ogv: "video/ogg",
  m4v: "video/mp4",
  mpeg: "video/mpeg",
  mpg: "video/mpeg",
  "3gp": "video/3gpp",
  "3g2": "video/3gpp2",

  // Documents
  pdf: "application/pdf",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ppt: "application/vnd.ms-powerpoint",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  odt: "application/vnd.oasis.opendocument.text",
  ods: "application/vnd.oasis.opendocument.spreadsheet",
  odp: "application/vnd.oasis.opendocument.presentation",
  pages: "application/vnd.apple.pages",
  numbers: "application/vnd.apple.numbers",
  keynote: "application/vnd.apple.keynote",
  epub: "application/epub+zip",

  // Text / Code
  txt: "text/plain",
  md: "text/markdown",
  markdown: "text/markdown",
  csv: "text/csv",
  tsv: "text/tab-separated-values",
  html: "text/html",
  htm: "text/html",
  xml: "application/xml",
  json: "application/json",
  jsonl: "application/jsonlines",
  yaml: "text/yaml",
  yml: "text/yaml",
  toml: "application/toml",
  ini: "text/plain",
  cfg: "text/plain",
  env: "text/plain",
  log: "text/plain",
  rtf: "application/rtf",
  css: "text/css",
  js: "text/javascript",
  mjs: "text/javascript",
  cjs: "text/javascript",
  ts: "application/typescript",
  tsx: "application/typescript",
  jsx: "text/javascript",
  py: "text/x-python",
  rb: "text/x-ruby",
  php: "application/x-httpd-php",
  java: "text/x-java-source",
  c: "text/x-c",
  cpp: "text/x-c++",
  h: "text/x-c",
  cs: "text/x-csharp",
  go: "text/x-go",
  rs: "text/x-rust",
  sh: "application/x-sh",
  bash: "application/x-sh",
  sql: "application/sql",

  // Archives
  zip: "application/zip",
  gz: "application/gzip",
  tar: "application/x-tar",
  bz2: "application/x-bzip2",
  xz: "application/x-xz",
  rar: "application/x-rar-compressed",
  "7z": "application/x-7z-compressed",

  // Fonts
  ttf: "font/ttf",
  otf: "font/otf",
  woff: "font/woff",
  woff2: "font/woff2",
  eot: "application/vnd.ms-fontobject",

  // Misc
  wasm: "application/wasm",
  swf: "application/x-shockwave-flash",
  db: "application/x-sqlite3",
  sqlite: "application/x-sqlite3",
};

export const MIME_CATEGORY_MAP: Array<[RegExp, MimeCategory]> = [
  [/^image\//, "image"],
  [/^audio\//, "audio"],
  [/^video\//, "video"],
  [/^font\//, "font"],
  [/^text\//, "text"],
  [/^application\/pdf$/, "pdf"],
  [/^application\/(json|xml|javascript|typescript|x-sh|sql|toml|wasm|rtf)/, "text"],
  [/spreadsheet|excel|\.sheet/, "spreadsheet"],
  [/presentation|powerpoint|\.presentation/, "presentation"],
  [/word|document|msword|odt|pages|epub/, "document"],
  [/zip|gzip|tar|bzip|rar|7z|xz/, "archive"],
  [/wasm|sqlite|x-elf|x-msdownload|octet-stream/, "binary"],
];

export const PLAIN_TEXT_MIMES = new Set([
  "text/plain",
  "text/markdown",
  "text/csv",
  "text/tab-separated-values",
  "text/html",
  "text/css",
  "text/javascript",
  "text/yaml",
  "text/x-python",
  "text/x-ruby",
  "text/x-c",
  "text/x-c++",
  "text/x-csharp",
  "text/x-go",
  "text/x-rust",
  "text/x-java-source",
  "application/json",
  "application/jsonlines",
  "application/xml",
  "application/javascript",
  "application/typescript",
  "application/x-sh",
  "application/sql",
  "application/toml",
  "application/rtf",
  "image/svg+xml",
]);

export const BROWSER_RENDERABLE_MIMES = new Set([
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
  "image/bmp",
  "image/svg+xml",
  "image/x-icon",
  "image/avif",
  "audio/mpeg",
  "audio/ogg",
  "audio/wav",
  "audio/flac",
  "audio/aac",
  "audio/mp4",
  "audio/webm",
  "video/mp4",
  "video/webm",
  "video/ogg",
  "application/pdf",
  "text/html",
  "text/plain",
  "text/css",
  "text/javascript",
]);
