/**
 * This entrie logic is generated by claude.
 */

import * as constants from "./constants";
import * as defs from "./typedef";
import * as detection from "./detection";
import * as helpers from "./helpers";
import * as resolvers from "./resolvers";
import * as utils from "./utils";

const mime = {
  ...constants,
  ...defs,
  ...detection,
  ...helpers,
  ...resolvers,
  ...utils,
};

export default mime;
